# Generated by Django 4.1.2 on 2022-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='links',
            name='img',
            field=models.ImageField(default='/static/img/bg-try.jpg', upload_to='core/static/links'),
        ),
    ]
