# Generated by Django 4.1.2 on 2022-10-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_links_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='tag',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'Javascript'), ('HTML', 'Html'), ('CSS', 'Css')], default='Python', max_length=10),
        ),
    ]
