# Generated by Django 4.1.2 on 2022-10-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_links_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='tag',
            field=models.CharField(choices=[('1', 'Python'), ('2', 'JavaScript'), ('3', 'HTML'), ('4', 'CSS')], default='1', max_length=10),
        ),
    ]
