# Generated by Django 4.1.2 on 2022-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_links_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='desc',
            field=models.CharField(max_length=300),
        ),
    ]
