# Generated by Django 4.1.2 on 2022-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_links_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
