# Generated by Django 4.1.2 on 2022-10-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_links_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='img',
            field=models.ImageField(default='/static/img/bg-try.jpg', upload_to='core/static/links'),
        ),
        migrations.AlterField(
            model_name='links',
            name='tag',
            field=models.CharField(choices=[('1', 'Python'), ('2', 'Media'), ('3', 'YouTube'), ('4', 'Courses')], default='1', max_length=10),
        ),
    ]
